set(CMAKE_C_COMPILER /opt/musl/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc)
set(CMAKE_CXX_COMPILER /opt/musl/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++)
set(CMAKE_AR /opt/musl/x86_64-linux-musl-cross/bin/x86_64-linux-musl-ar)
set(CMAKE_RANLIB /opt/musl/x86_64-linux-musl-cross/bin/x86_64-linux-musl-ranlib)
set(CMAKE_STRIP /opt/musl/x86_64-linux-musl-cross/bin/x86_64-linux-musl-strip)

set(CMAKE_FIND_ROOT_PATH /opt/musl/x86_64-linux-musl-cross/x86_64-linux-musl)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
